### ISSUE TITLE
BUG: invalid user|org / project name

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#154]
Took a quick pomodoro break and looked at the Hits homepage: https://hits.dwyl.com

Noticed that there are still strange entries, e.g:

```
Fri, 11 Mar 2022 10:45:02 /' | remove_first: 'http:/' }}{{ page.url }}.svg 3618
```
What even is that? 🤷‍♂️ 

Then there are the more innocuous but still incorrect ones:

```
Fri, 11 Mar 2022 10:43:12 /{mikel-brostrom}/{Yolov5_DeepSort_Pytorch}.svg 3562
Fri, 11 Mar 2022 10:06:13 /{cemac}/{SWIFTDB}.svg 22
```

![image](https://user-images.githubusercontent.com/194400/157852788-098a7683-b3eb-473f-9530-b45fb5d823d0.png)

I think we need to be more strict and actually _reject_ requests that have invalid `user|org` or `repo` ... 💭 
We should create a new badge e.g: ![hits-invalid-url](https://img.shields.io/badge/hits-invalid%20url-red?style=flat-square)

https://img.shields.io/badge/hits-invalid%20url-red?style=flat-square

# Todo

+ [x] Write tests that attempt to request an invalid url using the samples above
  + [x] Should return the "invalid url" badge
+ [x] Implement the fix 
+ [ ] Publish new version

**Comment by SimonLab** [comment]
username rules:
![image](https://user-images.githubusercontent.com/6057298/157866132-3585b2cd-4e18-4a1f-b576-79376aeefc50.png)

**Comment by nelsonic** [comment]
Indeed some form validation would go a long way. 
but people are *always* going to do URL manipulation so we need some server side validation of requested SVGs. 💭

**Comment by SimonLab** [comment]
I've created the following function to check the username and repository values:

```elixir
defp user_valid?(user), do: String.match?(user, ~r/^([[:alnum:]]+-)*[[:alnum:]]+$/)
defp repository_valid?(repo), do: String.match?(repo, ~r/^[[:alnum:]-_.]+$/)
```

**Comment by nelsonic** [comment]
Thanks for looking at this. 👍 
Definitely add comments for these functions and ref this issue. 💭

**Comment by nelsonic** [comment]
@SimonLab thanks for creating the PR: #155 
I think we need to have a _basic_ `404` page in the app explaining that the URL needs to be valid for the badge to work just to improve the UX for the people who _mistakenly_ created an invalid URL.

**Comment by SimonLab** [comment]
I've created a new error page:
![image](https://user-images.githubusercontent.com/6057298/158259908-1bb8bf5d-4c03-4cbe-9aee-7a0fd30ed10f.png)

When a badge is created the link will direct to "/user/repository":
![image](https://user-images.githubusercontent.com/6057298/158260285-11147c8d-f6cb-4133-80b8-03581bf5271b.png)

On this endpoint we check if the user and repository are valid and if not redirect to the new error page

**Comment by nelsonic** [comment]
Fixed. #155
