### ISSUE TITLE
Use Content Negotiation to Return JSON from Endpoint

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#168]
# Context

This project currently only allows one type of badge: [![HitCount](https://hits.dwyl.com/dwyl/hits-issue-168.svg?style=flat-square)](http://hits.dwyl.com/dwyl/hits-issue-168)
This **meets _our_ needs** because this is the style we use in our repos e.g: [dwyl/fields](https://github.com/dwyl/fields)

But there are other people in the community who find _other_ badge designs more appealing.
We want to help them get what they need. 

The way for us to enable other badge designs is via Shields Endpoint: https://shields.io/endpoint

# Todo

+ [x] Follow: https://github.com/dwyl/phoenix-content-negotiation-tutorial
+ [x] Use: https://github.com/dwyl/content
+ [x] Enable the hits endpoint to return `.json` 
e.g: 
```json
{
  "schemaVersion": 1,
  "label": "hits",
  "message": "420",
  "color": "brightgreen"
}
```

That way people can apply whatever style/color they want to their badge.

**Comment by avinayak** [comment]
Is it ok If I take up this task?

**Comment by nelsonic** [comment]
@avinayak yeah, the idea is that people can then use a Shields.io badge to have any size / appearance and even a logo! 💡 
So validating against their schema is a must. 👍 

I've invited you to be a contributor on this repo so you have **`write`** access and can create a branch directly on the repo which makes CI/colab easier. 🤞 
If you create a PR I can help. 🙏

**Comment by TF2CutContentWiki** [comment]
Oh wow, I didn't realize this issue was about the same thing I filed an issue report for.

**Comment by nelsonic** [comment]
@TF2CutContentWiki if you feel confident to create a branch and _start_ the pull request. You have write access to the repo. Describe what you want to achieve, take it as far as you can and we can help pick up any part where help is needed. 👌

**Comment by nelsonic** [comment]
On reflection, this is definitely _not_ a **`T1h`** task unless the person doing it is already _very_ familiar with **`Phoenix`** and _this_ (`Hits`) project. It's more like a **`T4h`** because the person doing the work has to [**Grok**](https://en.wikipedia.org/wiki/Grok) the code in _both_ the **`hits`** and **`content`** projects and that _alone_ is **`T1h`**. ⏳ 

@LuchoTurtle if you feel up to this challenge, please _first_ confirm that you've fully understood the requirements. 
i.e. if there is enough in the OP for you to start working on it. 🤞 
And if so, please assign it to yourself and add an **`in-progress`** label. 🏷️

**Comment by nelsonic** [comment]
@LuchoTurtle in preparation for https://github.com/dwyl/phoenix-todo-list-tutorial/issues/53 this could be a good issue to work on because the end result is a `REST API` (`JSON`) endpoint. 💭

**Comment by LuchoTurtle** [comment]
Just created a PR https://github.com/dwyl/hits/pull/204 that should address this.

I'm just writing a small write-up in the README. Similarly to the rest of the README, I don't go into much detail.

**Comment by nelsonic** [comment]
Updated. 
Deployed:

```sh
==> Monitoring deployment

 1 desired, 1 placed, 1 healthy, 0 unhealthy
--> v68 deployed successfully
```

https://shields.io/endpoint
![image](https://user-images.githubusercontent.com/194400/208450546-d5cc8134-024e-4bdd-9286-a074c7d58707.png)

Custom logos: https://github.com/badges/shields/blob/master/doc/logos.md

**Comment by nelsonic** [comment]
Try it! Head over to: https://shields.io/endpoint and paste `https://hits.dwyl.com/dwyl/hits.json` for the `url`
Then customise with a logo and colors:

![image](https://user-images.githubusercontent.com/194400/208468004-ed1112f3-4ca7-4477-a497-417be3fea9cb.png)


![Custom badge](https://img.shields.io/endpoint?color=%23fc0fc0%20&label=amaze&logo=elixir&logoColor=%23fc0fc0%20&style=for-the-badge&url=https%3A%2F%2Fhits.dwyl.com%2Fdwyl%2Fhits.json%3Fstyle%3Dflat-square%26show%3Dunique%26color%3Dpink)

Done. ✅

**Comment by LuchoTurtle** [comment]
Looks good to me!
![image](https://img.shields.io/endpoint?color=%23EEDCFC&label=%E3%80%90%3D%E2%97%88%EF%B8%BF%E2%97%88%3D%E3%80%91&logo=Linktree&logoColor=white&style=for-the-badge&url=https%3A%2F%2Fhits.dwyl.com%2Fdwyl%2Fhits.json)
