### ISSUE TITLE
Add "Hits" (Page View Counter) Badge to ALL @dwyl Repos/Projects so we can Chart Popularity Over Time

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#57]
The "Hits" project **_two_ goals** to:
a. **collect data** on view counts for our various projects/repositories so that we know how many people are _viewing / reading_ them. (_Sadly, **most people** don't [star](https://github.com/dwyl/stars) repos, even when they find them **useful**!_)
b. serve as ***example project*** that ***complete beginners*** can use to learn Node.js and [**Elixir**](https://github.com/dwyl/hits-elixir) with a "real world" application/use-case. 

## Todo:
+ [ ] _Manually_ add Hits Badge to our most popular repositories:

![image](https://user-images.githubusercontent.com/194400/32620473-b958afe2-c575-11e7-89d3-92de1a703090.png)

Bonus Level
+ [ ] write a _script_ that adds a Hits "Badge" to a repository `readme.md`.
+ [ ] and creates a Pull Request in the repo.

**Note**: We have _deliberately_ not "_publicised_" the "Hits Service" 
except for https://github.com/dwyl/repo-badges/tree/c2444c3a6d20d9f7fc381a471e7e20a8de8b94e9#github-repo-hit-counter-
and yet quite a _few_ non-dwyl people/projects appear to be using it:

![image](https://user-images.githubusercontent.com/194400/32609365-5b064d46-c557-11e7-9c19-9ade2b6ab941.png)

**Comment by nelsonic** [comment]
I think we have the badge on _most_ of our Repos now. 🎉 
@SimonLab if you spot a repo that doesn't have the badge or has a _broken_ one, please update. 
(_I will update if I see one ..._)
Thanks!
