### ISSUE TITLE
Why? What? How?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#66]
# _Why?_

Phoenix is awesome and a phoenix/elixir implementation will be _far_ more stable than the current (_node.js_) version which keeps crashing. 
see: https://github.com/dwyl/product-roadmap/issues/7 and https://github.com/dwyl/hits/issues/62, https://github.com/dwyl/hits/issues/63, https://github.com/dwyl/hits/issues/64 & https://github.com/dwyl/hits/issues/65

> **Note**: we _could_ add more error handling to the Node.js App and use PM2 to monitor the process see: https://github.com/dwyl/learn-devops/blob/master/nodejs-pm2-zero-downtime.md and we could _also_ migrate the `node.js` version to use PostgreSQL, but I feel that the app will be _considerably_ more robust in Phoenix.

> For anyone following along wondering why I'm pouring my time into this re-build when it isn't the _highest_ priority item on my [List](https://github.com/orgs/dwyl/projects/11?fullscreen=true) ... I'm doing it for the following reasons:
> + [x]  Right now we don't _have_ a Open Source App (_that we "Own" that we can invite contributions from the community ... there are several "Client" Apps that are Open Source and we are proud of e.g: [The Science Museum](https://github.com/TheScienceMuseum/collectionsonline), [Healthlocker (NHS)](https://github.com/healthlocker/healthlocker) and [Club Soda](https://github.com/club-soda/club-soda-guide) ... which people can read and learn from_) we want an App that is _useful_ to the community and we can invite people to contribute to because they will benefit directly from the improvements and practice their skills on a "real" app that is in Production and has *millions* of "Users".
  > We will have our own Mobile App _sooooon_ ... but in the meantime this is a _good_ way to introduce people to the @dwyl community. 

![image](https://user-images.githubusercontent.com/194400/57216027-8a99b080-6fe6-11e9-8658-22c719fef5c7.png)

# _What?_ 

Migrate the `node.js` Hits app https://github.com/dwyl/hits
to Phoenix using code written for https://github.com/dwyl/hits-elixir
Use a PostgreSQL database to store data so that we can run more interesting/advanced queries

# _How?_

Going to document this as go but the the outline is:

+ [x] ***First*** make sure I have the latest version of Phoenix! to avoid: https://github.com/dwyl/hits-nodejs/issues/3
see: https://hexdocs.pm/phoenix/installation.html#phoenix
```
mix archive.install hex phx_new 1.4.4
```
+ [x] Create app: `mix phx.new hits`
+ [x] Render Home Page (Static Content): https://github.com/dwyl/hits/issues/66#issuecomment-489399400 (_quick win_)
+ [x] Create `users` schema for storing `user` data:
```
mix phx.gen.schema User users name:string 
```
> The _two_ reasons I _was_ considering going with a single table is _speed_ and _simplicity_.
The fact that a GitHub repository can belong to a `user` or an `org` means that we need to determine this _before_ inserting the data ... but I think _for now_ we can just call it a `user` and we can determine the `type` later on (e.g: `user` or `org`). 👍 

+ [x] Create `repos` schema for storing `repo` data:
```
mix phx.gen.schema Repository repositories name:string user_id:references:users
```
+ [x] Create `useragents` schema for storing user agent data:
```
mix phx.gen.schema Useragent useragents name:string ip:string
```

+ [x] Create schema ~~_and_ HTML (views+templates)~~ `hits` for storing _and_ viewing hit data:
```
mix phx.gen.schema Hit hits repo_id:references:repositories useragent_id:references:useragents
```

+ [x] Create endpoint for "happy path" `/:user/:repository`
  + [x] should render an svg badge
  + [x] Edge Cases: GOTO: https://github.com/dwyl/hits/issues/67
+ [x] Extract the metadata (`useragent` and `ip` address) from the `conn` headers:
https://github.com/dwyl/hits-elixir/blob/b2ed9c10aabc20a36f24c185a5f2a9831b1652d3/lib/hits.ex#L45-L54

+ [x] **`INSERT`** the `hit` into the dabase
+ [x] Query PostgreSQL for the hit count for that repo #71 
+ [x] Create the SVG using string interpolation: 
https://github.com/dwyl/hits-elixir/blob/b2ed9c10aabc20a36f24c185a5f2a9831b1652d3/lib/hits.ex#L29-L31
+ [x] Return the SVG
+ [x] Update screenshots to reflect change in TCP Port `8080` > `4000`

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/57163337-d252e900-6de8-11e9-9182-1e9ec243e814.png)
Fixed by adding the `/hits` resource to the `router.ex` file and now these tests pass. ✅ 

Onto the next failing test:
![image](https://user-images.githubusercontent.com/194400/57163782-0ed31480-6dea-11e9-9bbb-9ac4521a33e8.png)

Continue tomorrow: `mix test test/hits_web/controllers/hit_controller_test.exs:40`

**Comment by nelsonic** [comment]
You will see that _four_ tests are failing:

![image](https://user-images.githubusercontent.com/194400/57181235-f8c86100-6e88-11e9-94f6-be5bac514c48.png)

![image](https://user-images.githubusercontent.com/194400/57181215-af781180-6e88-11e9-8a08-b1ff122edf3a.png)

**Comment by nelsonic** [comment]
Home page (_static content_) served by Phoenix:
![image](https://user-images.githubusercontent.com/194400/57190244-24425e80-6f10-11e9-99ce-41ab7c1e00a1.png)

Need to tidy up the padding around the body and width of inputs ... but it's working. 👍

**Comment by nelsonic** [comment]
The issue was conflicting styles from Phoenix `app.css` which I've commented out.
![image](https://user-images.githubusercontent.com/194400/57190494-a7fd4a80-6f12-11e9-97ed-4b056d394487.png)

**Comment by nelsonic** [comment]
ER Diagram after creating schema:
![hits-basic-ER-diagram](https://user-images.githubusercontent.com/194400/57219336-a5245780-6fef-11e9-8cbd-ea4be9a38ca0.png)

**Comment by nelsonic** [comment]
Decided to add the DBeaver UI as _context_ to help people understand how to _find_ the ER diagram:
![hits_dev-ER-diagram-expanded](https://user-images.githubusercontent.com/194400/57219542-51fed480-6ff0-11e9-8192-280cd6d492c7.png)

**Comment by nelsonic** [comment]
Having the DBeaver "Quick Access" UI on the next line because I constrained the width of the window was bugging me! So I expanded the window and re-took the screenshot:
![hits-er-diagram](https://user-images.githubusercontent.com/194400/57219989-b1a9af80-6ff1-11e9-8968-e3b76428093d.png)

(I think I have an OCD problem with screenshots ... 🙄humour me and play spot-the-difference ... 😜) 

Also took a screenshot of the Schema Migrations table to give some insight:
![hits-schema-migrations](https://user-images.githubusercontent.com/194400/57219813-347e3a80-6ff1-11e9-95bb-73ffbceea22b.png)

**Comment by nelsonic** [comment]
Continue: https://hexdocs.pm/phoenix/contexts.html

**Comment by nelsonic** [comment]
After reading about contexts, I've concluded that they aren't useful in the Hits app (_at least for the foreseeable future_) so I'm going to back-track a step and do a `mix phx.gen.schema` instead of `mix phx.gen.html` for the Hits table/schema. That will both reduce the noise from unnecessary files (_that I was just going to have to delete_) and remove the failing tests which would have _definitely_ put beginners off.

**Comment by nelsonic** [comment]
lib/hits_web/templates/layout/app.html.eex
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Hits</title>
    <!-- <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/> -->
    <link rel="stylesheet" href="https://unpkg.com/tachyons@4.8.0/css/tachyons.min.css"/>
  </head>
  <body class="">
    <main role="main"">
      <!-- <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p> -->
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>
```

lib/hits_web/templates/page/index.html.eex
```html
<h2 class="bg-teal white h-25 tc ttu f1 lh-title lh-solid mt0 pa2 pb3 mb0 pb0">
  Hits!
  <a href="http://hits.dwyl.io/" >
    <img src="http://hits.dwyl.io/homepage.svg" alt="Hit Count" class="pa0 ba bw1 b--white">
  </a>
</h2>
<h4 class="mt0 tc fw5 f5 teal pa2 mb0">
  The <em>easy</em> way to know how many people are
  <strong><em>viewing</em></strong> your GitHub projects!
</h4>

<h2 class="mt0 fw5 tc f2 bg-teal white pa2"><em>How?</em></h2>
<div id="how" class="dn pa3">

  <table class="collapse pv2 ph3 w-100 pa4">
    <tr class="bb-0">
      <td class="pv2 ph3 w-30">
        Input your <strong class="fw5">GitHub Username</strong>
        (<em> <strong class="u">or</strong> org name</em>):
      </td>
      <td class="pv2 ph3 w-30">
        <input class="input-reset f4 pa2 ba mr5 w-80" type="text"
        id="username" name="username" placeholder="username" autofocus maxlength="50">
      </td>
    </tr>
    <tr class="">
      <td class="pv2 ph3 w-40">
        Input the <strong class="fw5">GitHub Project/Repository</strong>
        name:
      </td>
      <td class="pv2 ph3 w-40">
        <input class="input-reset f4 pa2 ba mr5 w-80" type="text"
        id="repo" name="repo" placeholder="repo/project" maxlength="100">
      </td>
    </tr>
  </table>
</div>

<h3 class="mt3 fw5 tc db f3 bg-teal white pa2">Your Badge <em>Markdown:</em></h3>
<pre id="badge" class="fw4 ba bw1 pa3 ma2" style="white-space: pre-wrap; word-break: keep-all;">
  [![HitCount](http://hits.dwyl.io/{username}/{repo}.svg)](http://hits.dwyl.io/{username}/{repo})
</pre>

<p class="pl2" id="nojs">
  Using the above markdown as a template, <br />
  <em>Replace</em> the <strong class="code">{username}</strong> with <em>your</em> GitHub username <br />
  <em>Replace</em> the <strong class="code">{repo}</strong> with the repo name.
</p>

<p class="pl2 ml2">
<em>Copy</em> the markdown snippet and <em>Paste</em> it into your
<strong class="code">README.md</strong> file <br />
  to start tracking the view count on your GitHub project!
</p>

<h2 class="mt0 fw5 tc f4 bg-teal white pa2 mt5"><em>Recently</em> Viewed Projects (<em>tracked by Hits</em>)</h2>
<div class="h5 pl2" id='hits'>
  <div style="display:none">Dummy Child Node for insertBefore to work</div>
</div>

<style>
  .teal {
    color: #4DB6AC;
  }
  .bg-teal {
    background: #4DB6AC;
  }
  body { /* dwyl font */
    font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
  }
</style>
```
app.js
```js
// Markdown Template
var mt = '[![HitCount](http://hits.dwyl.io/{user}/{repo}.svg)](http://hits.dwyl.io/{user}/{repo})';

function generate_markdown () {
  var user = document.getElementById("username").value || '{username}';
  var repo = document.getElementById("repo").value || '{project}';
  // console.log('user: ', user, 'repo: ', repo);
  user = user.replace(/[.*+?^$<>()|[\]\\]/g, '');
  repo = repo.replace(/[.*+?^$<>()|[\]\\]/g, '');
  return mt.replace(/{user}/g, user).replace(/{repo}/g, repo);
}

function display_badge_markdown () {
  var md = generate_markdown()
  var pre = document.getElementById("badge").innerHTML = md;
}

setTimeout(function () {
  // show form if JS available (progressive enhancement)
  document.getElementById("how").classList.remove('dn');
  document.getElementById("nojs").classList.add('dn');
  display_badge_markdown(); // render initial markdown template
  var get = document.getElementsByTagName('input');
 for (var i = 0; i < get.length; i++) {
     get[i].addEventListener('keyup', display_badge_markdown, false);
     get[i].addEventListener('keyup', display_badge_markdown, false);
 }
}, 500);
```

Start from scratch (_keeping meta files and `README.md`_...)
```
 git rm -r assets/ config/ lib/ priv/ test/
```

**Comment by nelsonic** [comment]
The effect of starting again from scratch is fewer lines of code in the project, that's a good thing:
![image](https://user-images.githubusercontent.com/194400/57683659-0f5e7d00-762c-11e9-8915-9996be54340a.png)

**Comment by nelsonic** [comment]
Static homepage:
![image](https://user-images.githubusercontent.com/194400/57684208-3ff2e680-762d-11e9-89c4-0b0d04694f5a.png)

**Comment by nelsonic** [comment]
Failing test:
![failing-test](https://user-images.githubusercontent.com/194400/57686427-7f233680-7631-11e9-83ef-931016d7b68b.png)

Passing:
![hits-static-page-test-passing](https://user-images.githubusercontent.com/194400/57686862-46d02800-7632-11e9-8be0-76e46c4d1cd9.png)

**Comment by nelsonic** [comment]
https://travis-ci.org/dwyl/hits/builds/532202304#L680

```sh
$ mix cover
** (Mix) The task "cover" could not be found
The command "mix cover" exited with 1.
```

![image](https://user-images.githubusercontent.com/194400/57688623-d3c8b080-7635-11e9-81b7-63de7e249a51.png)


add the following line to `mix.exs`
```elixir
      # tracking test coverage
      {:excoveralls, "~> 0.7.0", only: [:test, :dev]},
```

**Comment by nelsonic** [comment]
Tests passing but coverage is low ...
![image](https://user-images.githubusercontent.com/194400/57689572-a5e46b80-7637-11e9-91a9-a28d7ca2c48a.png)

![image](https://user-images.githubusercontent.com/194400/57689597-b72d7800-7637-11e9-847e-fd016c9032ad.png)

**Comment by nelsonic** [comment]
Updated screenshot:
![image](https://user-images.githubusercontent.com/194400/57912373-0b2b9d00-7882-11e9-8dfd-df1021e9d076.png)

**Comment by nelsonic** [comment]
Feature parity achieved:
![image](https://user-images.githubusercontent.com/194400/57980330-26cda980-7a22-11e9-9494-594dbd1acae3.png)

**Comment by nelsonic** [comment]
Updated screenshots:

![hits-example-badge](https://user-images.githubusercontent.com/194400/57980413-57faa980-7a23-11e9-91cd-cc9e106be1ee.png)

![hit-count-42](https://user-images.githubusercontent.com/194400/57980416-62b53e80-7a23-11e9-948a-7c423ecb18c1.png)

**Comment by nelsonic** [comment]
![draw-the-owl](https://user-images.githubusercontent.com/194400/58163421-e6696800-7c7b-11e9-93d3-73af6486d8e1.png)

**Comment by nelsonic** [comment]
If you are interested in a step-by-step tutorial/example, leave a comment on https://github.com/dwyl/hits/issues/74

**Comment by nelsonic** [comment]
This issue is now complete. Closing. ✅
