### ISSUE TITLE
Performance Optimisation: Use EEX Template for SVG Rendering

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#70]
At present we have a 511 Byte [`template.svg`](https://github.com/dwyl/hits-elixir/blob/master/lib/template.svg) file which we are _manually_ [`String.replace`](https://github.com/dwyl/hits-elixir/blob/12e7f9a9f84d9341c022320587da29b88b7f940e/lib/hits.ex#L30)-ing the `{count}` in:

```
 String.replace(svg_badge_template(), ~r/{count}/, to_string(count))
```

This does not take advantage of Phoenix's template compilation for faster rendering.

# Todo

+ [ ] refactor template to `badge.svg.eex` 
+ [ ] render using `render(conn, "badge.svg", count)`
+ [ ] apply gzip compression for even faster rendering

> _**Note**: rendering is **not** currently a "bottleneck" in the app,
 the DB query is orders of magnitude slower than `String.replace`. 
This optimisation should be considered `after` ETS is implemented for caching the count._

**Comment by nelsonic** [comment]
Using the `String.replace` method, the response time on `localhost` is around **`500µs`**:
![image](https://user-images.githubusercontent.com/194400/57965629-b437cd80-793e-11e9-89cf-287a1f4fd367.png)

That's **`µs`** _not_ **`ms`** ... 500 [microseconds](https://en.wikipedia.org/wiki/Microsecond) ... 500 _millionths_ of a second.

We can _definitely_ speed this up, and it would be good to do a more scientific benchmark of response times ... but I don't think any one is going to _complain_ about this response time. 😉 

Still if you have time to help refactor this, please dive in! 💻
