### ISSUE TITLE
Add Channel for RealTime Updates

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#79]
The final element for achieving feature parity between the Node.js MVP and the Phoenix version is to add WebSockets to stream the hits to the client as they come in:
![image](https://user-images.githubusercontent.com/194400/58368708-9216f000-7ee8-11e9-80bc-bde78f653c91.png)

# Todo
+ [x] send notification to client for each hit.
  + [x] user, project, count

Relevant links:
+ [x] https://github.com/dwyl/phoenix-chat-example#2-create-the-websocket-channel
+ [x] https://github.com/dwyl/hits-elixir/blob/master/lib/websocket_handler.ex

**Comment by nelsonic** [comment]
Refreshing my knowledge by reading https://hexdocs.pm/phoenix/channels.html 👀

**Comment by nelsonic** [comment]
At this stage we don't want to send messages from the Client to the Server (_this is not "Chat"_)
rather we want to send messages from the Server to the Client (_when a hit event happens_)
so I searched for "phoenix channel send from server" and found:
How to broadcast a message from a Phoenix Controller to a Channel?
https://stackoverflow.com/questions/33960207/how-to-broadcast-a-message-from-a-phoenix-controller-to-a-channel

use `MyApp.Endpoint.broadcast(topic, event, msg)`
https://hexdocs.pm/phoenix/Phoenix.Endpoint.html
https://hexdocs.pm/phoenix/Phoenix.Socket.Broadcast.html

**Comment by nelsonic** [comment]
This post looks promising: https://code.likeagirl.io/how-to-make-a-server-side-timer-with-phoenix-websockets-96d0e1e56f2d

**Comment by nelsonic** [comment]
Works:
![image](https://user-images.githubusercontent.com/194400/58618424-86497600-82ba-11e9-80f6-653d9afc4e0b.png)
